name: Packer Builder

on:
  workflow_dispatch:

  pull_request:
    branches:
      - "release"
      - "build"

  push:
    branches:
      - "release"
      - "build"

jobs:
  packer_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Packer build
        uses: ExitoLab/packer_build_action_aws@v0.2.10
        with:
          templateFile: "ami.json"
          workingDir: "ami"
          varFile: "variables.json"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
